language: objective-c

branches:
 only:
 - master

xcode_workspace: CleanWeather.xcworkspace
xcode_scheme: CleanWeather
osx_image: xcode7.1
xcode_sdk: iphonesimulator

script:
- xcodebuild -workspace CleanWeather.xcworkspace -scheme CleanWeather -sdk iphonesimulator build test
